export const init = jest.fn();
export const captureException = jest.fn();
export const captureMessage = jest.fn();
export const addBreadcrumb = jest.fn();
export const setUser = jest.fn();
export const setTag = jest.fn();
export const setContext = jest.fn();
export const wrap = jest.fn((comp) => comp);
export const reactNavigationIntegration = jest.fn();
export const reactNativeTracingIntegration = jest.fn();
